project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Public Safety Insights: NYPD Complaint Data for 2023"
  author:
    - Weilun Chen (wc2885)
    - Ariel Lin (al4735)
  repo-url: https://github.com/linariel6/NYPDComplaintAnalysis
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


