```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
```


```{r}
data <- read.csv('/Users/ariellin/Documents/EDAV/FinalProject/NYPD_Complaint_Data_Historic_20241118.csv')
# head(data)
```
```{r}
dim(data)
```
```{r}
# Null values may also appear in instances where
# information was not available or unknown at the time of the report and should be
# considered as either “Unknown/Not Available/Not Reported.”

# glimpse(data)
# 
# unique(data$SUSP_SEX)
# unique(data$VIC_SEX)
```
```{r}
data <- data |> 
  mutate(across(everything(), ~ replace(., . %in% c('(null)', 'UNKNOWN'), NA)))

sort(colSums(is.na(data)) / nrow(data) * 100)

```
```{r}
#| fig-width: 8
#| fig-height: 8
#| 
# glimpse(data)
missing_percent <- colSums(is.na(data)) / nrow(data) * 100
missing_data <- data.frame(Column = names(data), Missing_Percent = missing_percent)

ggplot(missing_data, aes(x = reorder(Column, -Missing_Percent), y = Missing_Percent)) +
  geom_bar(stat = "identity", fill = "lightskyblue", color = "black", width = 0.8) +
  coord_flip() +
  labs(title = "NYPD Complaint 2023 Dataset: Missing Values % by Column",
       x = "Column Name", y = "Missing Data (%)") +
  theme_minimal() 

ggsave("plot1.png", width = 8, height = 8, path = "Plots/")

```
```{r}
library(lubridate)
data$CMPLNT_FR_DT <- mdy(data$CMPLNT_FR_DT) 
```


```{r}
#| fig-width: 8
#| fig-height: 8
monthly_missing <- data |> 
  mutate(
    Month = floor_date(CMPLNT_FR_DT, "month"), 
    Total_NA = rowSums(is.na(data))            
  ) |>
  group_by(Month) |> 
  summarize(Missing_Count = sum(Total_NA, na.rm = TRUE))

ggplot(monthly_missing, aes(x = Month, y = Missing_Count)) +
  geom_bar(stat = "identity", fill = "lightskyblue", color = "black") +
  labs(
    title = "Total Missing Values by Month",
    x = "Month",
    y = "Total Missing Values"
  ) +
  theme_minimal()

ggsave("plot2.png", width = 8, height = 4, path = "Plots/")
```
```{r}
#| fig-width: 15
#| fig-height: 15

missing_cols <- data[, colSums(is.na(data)) > 0]
missing_matrix <- as.data.frame(is.na(missing_cols))
missing_corr <- cor(missing_matrix, use = "pairwise.complete.obs")
library(corrplot)

png(filename = "Plots/plot3.png", width = 2500, height = 2500, res = 150)
corrplot(missing_corr, method = "color", type = "upper",
         tl.col = "black", tl.srt = 45, 
         addCoef.col = "darkgray",
         mar = c(5, 4, 4, 2))   
dev.off()

```

